# # Docker
# # Build a Docker image
# # https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
# - main

# resources:
# - repo: self


# stages:
# - stage: CI_CD
#   displayName: CI_CD
#   jobs:
#   - job: CI_CD
#     displayName: CI/CD
#     pool: Eslam2
#     steps:

# # Build custom docker image
#     - task: CmdLine@2
#       displayName: Build image
#       inputs:
#         script: 'docker build -t eslam411/aastmt:latest ./aastmt/'

# # Push to docker hub
#     - task: CmdLine@2
#       displayName: Push image
#       inputs:
#         script: 'docker push eslam411/aastmt:latest'

# # Deploy the app to the AKS
#     - task: KubernetesManifest@1
#       inputs:
#         action: 'deploy'
#         connectionType: 'kubernetesServiceConnection'
#         kubernetesServiceConnection: 'eslamaks-eslamaks-test-1702147657190'
#         namespace: 'test'
#         manifests: './aastmt/k8s/*'





trigger:
- main

stages:
- stage: TerraformApply
  jobs:
  - job: Terraform
    pool: Eslam2
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/aastmt/terraform'
        command: 'init'
        environmentServiceNameAzureRM: 'azure-service-connection'
        backendServiceArm: 'azure-service-connection'
        
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/aastmt/terraform'
        command: 'apply'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'azure-service-connection'
        backendServiceArm: 'azure-service-connection'

- stage: KubernetesDeploy
  jobs:
  - deployment: Deploy
    pool: Eslam2
    environment: 'AASTMT'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: 'azure-service-connection'
              azureResourceGroup: 'EslamRes1'
              kubernetesCluster: 'terraform-aks1'
              command: 'apply'
              useConfigurationFile: true
              configuration: './aastmt/k8s/*'
