# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self


stages:
- stage: CI_CD
  displayName: CI_CD
  jobs:
  - job: CI_CD
    displayName: CI/CD
    pool: Eslam2
    steps:

# Build custom docker image
    - task: CmdLine@2
      displayName: Build image
      inputs:
        script: 'docker build -t eslam411/aastmt:latest ./aastmt/'

# Push to docker hub
    - task: CmdLine@2
      displayName: Push image
      inputs:
        script: 'docker push eslam411/aastmt:latest'

# Deploy the app to the AKS
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'eslamaks-eslamaks-test-1702147657190'
        namespace: 'test'
        manifests: './aastmt/k8s/*'