# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Eslam
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/aastmt/Dockerfile'
        tags: eslam411/aastmt:latest

# Push to docker hub
  - job: DockerHub
    displayName: Push to docker hub
    pool: Eslam
    steps:
    - task: CmdLine@2
      displayName: Push image
      inputs:
        script: 'docker push eslam411/aastmt:latest'

#  CD to k8s
