apiVersion: apps/v1
kind: Deployment
metadata:
  name: aastmt
  namespace: aastmt
spec:
  selector:
    matchLabels:
      app: aastmt
  template:
    metadata:
      labels:
        app: aastmt
    spec:
      containers:
      - name: aastmt
        image: aastmt:test
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: aastmt
spec:
  selector:
    app: aastmt
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

